### ISSUE TITLE
Add 'Tabs' indentation settings support

### ISSUE THREAD

**Issue by ite-klass** [SLaks/Rebracer#16]
Please add support for indentation settings (sharing on a per-solution basis).

Editorconfig seems to be advertised as an alternative to this, but its not.

The editorconfig plugin specifies indentation settings on a per-file level rather than per-language as VS does. Hence, it can not be a complete replacement.

Furthermore, we’re using ReSharper to format code, which in turn uses the VS settings. So we actually need the VS settings to be set up to what we want it to be.

And worse still, does one of

* as I was told in a comment on the github tracker: the editorconfig plugin changes settings temporarily for one file when it is opened until it loses focus
* as I could determine through testing with VS2013 it sets VS langauge specific settings when opening a file - but never undoes these (different state of settings depending on which files you opened when)

With all these problems editorconfig is not a viable alternative.
What we would actually need is Rebracer to support the Tabs settings.

**Comment by SLaks** [comment]
You can manually add tabs settings to your `Rebracer.xml`, as [mentioned](https://github.com/SLaks/Rebracer#faq) in the Readme.

Once you add that section, Rebracer will handle the setting like any other setting.

**Comment by ite-klass** [comment]
Ah, I didn’t find that when searching for `indent`.
Thanks.

**Comment by ite-klass** [comment]
How are the other settings named? Where can I look them up?
Specifically tab size and indent size.

**Comment by SLaks** [comment]
Note that editorconfig can also specify settings per-language; just use `**/*.xml`.

**Comment by ite-klass** [comment]
Huh? Like `[**/*.xml]`?
Is this a VS plugin specific hack?
Is that documented anywhere?

Why would it not just be specific to files ending in `.xml` then?

The editorconfig VS plugins issues of applying only on opening files, and leaking the setting (not resetting; bug) still persist.

**Comment by SLaks** [comment]
You want to apply to all XML editors, regardless of extension?
I misunderstood.

**Comment by CADbloke** [comment]
https://gist.github.com/CADbloke/6206b1d4084a88473689 is a list to add for all the indents.

**Comment by macinta** [comment]
@SLaks I think the FAQ entry on this has a typo.  There's currently a "name" attribute in the closing "ToolsOptionsSubCategory" tag.  The setting didn't work for me until I removed that attribute.

Also, I think I prefer using Rebracer for managing indentation over Editorconfig because Editorconfig (from what I've read) changes the global settings and leaves them that way.  The downside to that is that you have to create an Editorconfig settings file for every project then, otherwise opening the one oddball project which uses different settings will change the defaults used by any project that follows.  I like how Rebracer allows you to keep the global defaults.

**Comment by macinta** [comment]
Hmmm, I guess I spoke too soon.  It seems that my VS defaults do get changed when using the "InsertTab" XML from the FAQ.  I assume that's because it's a manual entry.
